/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.project;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ubaid ur rehman
 */
public class AddRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddRecord
     */
    public AddRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        studentname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentdept = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        borrowbook = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tillend = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        backtostudentrecord = new javax.swing.JButton();
        dateofissue = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        studentid.setToolTipText("");
        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });
        jPanel1.add(studentid);
        studentid.setBounds(340, 120, 240, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 130, 290, 20);

        studentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnameActionPerformed(evt);
            }
        });
        jPanel1.add(studentname);
        studentname.setBounds(340, 180, 240, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 180, 160, 30);
        jPanel1.add(studentdept);
        studentdept.setBounds(340, 240, 240, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 240, 300, 20);

        borrowbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbookActionPerformed(evt);
            }
        });
        jPanel1.add(borrowbook);
        borrowbook.setBounds(340, 290, 240, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name of Borrow Book");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 290, 310, 30);

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.setToolTipText("Add it");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(410, 460, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Issue");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 360, 180, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Till End");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 410, 120, 22);
        jPanel1.add(tillend);
        tillend.setBounds(340, 410, 240, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Record");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 50, 300, 40);

        backtostudentrecord.setForeground(new java.awt.Color(255, 255, 255));
        backtostudentrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Icons/Mix Icon/Home.png"))); // NOI18N
        backtostudentrecord.setToolTipText("Back to StudentRecord");
        backtostudentrecord.setBorderPainted(false);
        backtostudentrecord.setContentAreaFilled(false);
        backtostudentrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtostudentrecordActionPerformed(evt);
            }
        });
        jPanel1.add(backtostudentrecord);
        backtostudentrecord.setBounds(30, 30, 20, 30);
        jPanel1.add(dateofissue);
        dateofissue.setBounds(340, 350, 240, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Project BackGround/download.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtostudentrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtostudentrecordActionPerformed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecord().setVisible(true);
            }
        });
    }//GEN-LAST:event_backtostudentrecordActionPerformed

    private void borrowbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowbookActionPerformed

    private void studentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnameActionPerformed

    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_studentidActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String id = studentid.getText();
        String name = studentname.getText();
        String Departmentname = studentdept.getText();
        String Borrowbook = borrowbook.getText();
        String DOI = dateofissue.getDate().toString();
        String DOE = tillend.getDate().toString();
        DOI = prprocess(DOI);
        DOE = prprocess(DOE);
        if(studentid.getText().equals("")&&studentname.getText().equals("")&&studentdept.getText().equals("")&&borrowbook.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Sorry We Cannot Add Empty Data");
        }
        else
        {
        int yesOrNo = JOptionPane.showConfirmDialog(this, "Do you save this Record", "Save Record ", WIDTH);
        //JOptionPane.showMessageDialog(this, yesOrNo+"","hsdfbsjdb", WIDTH);
        System.out.println(yesOrNo);
        if (yesOrNo == 0) {
            FileWriter f = null;
            BufferedWriter b = null;
            
            
            
            FileReader fr=null;
            BufferedReader br=null;
            
            boolean flag=false;
            String bname,bauthorname,bbookedition;
            try {
                fr=new FileReader("Book.txt");
                br=new BufferedReader(fr);
                f = new FileWriter("Student.txt", true);
                b = new BufferedWriter(f);
                while((bname=br.readLine())!=null)
                {    
                    bname=bname+"\n";
                    bauthorname=br.readLine()+"\n";
                    bbookedition=br.readLine()+"\n";
                 if(bname.equals(borrowbook.getText()+"\n"))
                 {
                    flag=true;

                    b.write(id);
                    b.newLine();
                    b.write(name);
                    b.newLine();
                    b.write(Departmentname);
                    b.newLine();
                    b.write(Borrowbook);
                    b.newLine();
                    b.write(DOI);
                    b.newLine();
                    b.write(DOE);
                    b.newLine();
                    int result = JOptionPane.showConfirmDialog(this, "Data Successfully Added!", "Confirm Dialog", JOptionPane.OK_CANCEL_OPTION, WIDTH);
                    if (result == 0) {

                        studentid.setText("");
                        studentname.setText("");
                        studentdept.setText("");
                        borrowbook.setText("");
                        dateofissue.setDateFormatString("");
                        tillend.setDateFormatString("");

                    }
                }
                }
                if(flag==false)
                {
                    JOptionPane.showMessageDialog(this,"Sorry! The Book isn't Found in Books");
                }
            
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                if (b != null) {
                    try {
                        b.close();
                    } catch (IOException ex) {
                        Logger.getLogger(AddRecord.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (f != null) {
                    try {
                        f.close();
                    } catch (IOException ex) {
                        Logger.getLogger(AddRecord.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton backtostudentrecord;
    private javax.swing.JTextField borrowbook;
    private com.toedter.calendar.JDateChooser dateofissue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField studentdept;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField studentname;
    private com.toedter.calendar.JDateChooser tillend;
    // End of variables declaration//GEN-END:variables

    private String prprocess(String DOE) {
        String temp = "";

        StringTokenizer tokens = new StringTokenizer(DOE);

        tokens.nextToken();

        temp += tokens.nextToken() + " ";

        temp += tokens.nextToken() + " ";

        tokens.nextToken();

        tokens.nextToken();
        temp += tokens.nextToken();

        return temp;
    }
}
