/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.project;

import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ubaid ur rehman
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        button();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        createname = new javax.swing.JTextField();
        createusername = new javax.swing.JTextField();
        createpassword = new javax.swing.JPasswordField();
        createconfirmpassword = new javax.swing.JPasswordField();
        Create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createdate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        backtologinform = new javax.swing.JButton();
        emailaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        createname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createname.setForeground(new java.awt.Color(204, 204, 204));
        createname.setText("Name");
        createname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                createnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                createnameFocusLost(evt);
            }
        });
        createname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnameActionPerformed(evt);
            }
        });
        jPanel2.add(createname);
        createname.setBounds(390, 150, 290, 40);

        createusername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createusername.setForeground(new java.awt.Color(204, 204, 204));
        createusername.setText("Username");
        createusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                createusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                createusernameFocusLost(evt);
            }
        });
        jPanel2.add(createusername);
        createusername.setBounds(390, 220, 290, 40);

        createpassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(createpassword);
        createpassword.setBounds(390, 340, 290, 40);

        createconfirmpassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(createconfirmpassword);
        createconfirmpassword.setBounds(390, 410, 290, 40);

        Create.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Create");
        Create.setBorderPainted(false);
        Create.setContentAreaFilled(false);
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        jPanel2.add(Create);
        Create.setBounds(760, 520, 120, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jLabel1.setToolTipText("FirstName and LastName");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 150, 100, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jLabel3.setToolTipText("Create Username");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(240, 220, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(230, 350, 140, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(130, 410, 240, 40);

        createdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                createdateFocusGained(evt);
            }
        });
        jPanel2.add(createdate);
        createdate.setBounds(390, 470, 290, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(200, 480, 200, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Create Account");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(380, 40, 330, 60);

        male.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.setContentAreaFilled(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male);
        male.setBounds(420, 520, 90, 33);

        female.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.setContentAreaFilled(false);
        jPanel2.add(female);
        female.setBounds(540, 520, 120, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jLabel8.setToolTipText("Select One");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(270, 510, 90, 50);

        backtologinform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Icons/Mix Icon/Home.png"))); // NOI18N
        backtologinform.setText("Home");
        backtologinform.setToolTipText("Back to the Previous Page");
        backtologinform.setBorderPainted(false);
        backtologinform.setContentAreaFilled(false);
        backtologinform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologinformActionPerformed(evt);
            }
        });
        jPanel2.add(backtologinform);
        backtologinform.setBounds(40, 30, 87, 40);

        emailaddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(emailaddress);
        emailaddress.setBounds(390, 280, 290, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email Address");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(180, 280, 200, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Project BackGround/336099_library-book-wallpaper.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1040, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void button()
    {
        ButtonGroup bg=new ButtonGroup();
        bg.add(male);
        bg.add(female);
    }
    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void backtologinformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologinformActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Firstpage().setVisible(true);
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_backtologinformActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        int yesOrNo = JOptionPane.showConfirmDialog(this, "Do you want Create", "Create Account ", WIDTH);
        if(yesOrNo==0)
        {
        FileWriter fw=null;
        BufferedWriter bw=null;
        String name,username,email,password,confirmpassword,DOB;
        String gender="";
        boolean flag=false;
        try
        {
            fw=new FileWriter("Employee.txt",true);
            bw=new BufferedWriter(fw);
            name=createname.getText();
            username=createusername.getText();
            email=emailaddress.getText();
            password=createpassword.getText();
            confirmpassword=createconfirmpassword.getText();
            DOB=createdate.getDate().toString();
            DOB = prprocess(DOB);
            if(male.isSelected())
            {
                
                gender=male.getText();
            }
            if(female.isSelected())
            {
               
                gender=female.getText();
            }
            
            if(password.equals(confirmpassword))
            {    
            bw.write(name);
            bw.newLine();
            bw.write(username);
            bw.newLine();
            bw.write(email);
            bw.newLine();
            bw.write(password);
            bw.newLine();
//            if(password.equals(confirmpassword))
//            {
//                bw.write(password);
////                bw.newLine();
////                bw.write(confirmpassword);
//                bw.newLine();
//            }
            bw.write(DOB);
            bw.newLine();
            bw.write(gender);
            bw.newLine();
            int result = JOptionPane.showConfirmDialog(this, "Account Successfully Created!", "Confirm Dialog", JOptionPane.OK_CANCEL_OPTION, WIDTH);
                    if (result == 0) {
                      dispose();
                      java.awt.EventQueue.invokeLater(new Runnable() {
                          public void run() {
                          new Firstpage().setVisible(true);
                         }
                      });
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Those passwords didn't match. Try again");
            }
        } catch (IOException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(bw!=null)
                try {
                    bw.close();
            } catch (IOException ex) {
                Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(fw!=null)
                try {
                    fw.close();
            } catch (IOException ex) {
                Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_CreateActionPerformed

    private void createnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnameActionPerformed
        

        // TODO add your handling code here:
    }//GEN-LAST:event_createnameActionPerformed

    private void createnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createnameFocusGained
        if(createname.getText().equals("Name"))
             {
                    createname.setText("");
             }
        createname.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_createnameFocusGained
    
    private void createnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createnameFocusLost
        if(createname.getText().equals(""))
             {
                    createname.setText("Name");
             }
             createname.setForeground(new Color(204,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_createnameFocusLost

    private void createusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createusernameFocusGained
        // TODO add your handling code here:
        if(createusername.getText().equals("Username"))
                {
                   createusername.setText("");
                }
        createusername.setForeground(Color.BLACK);
    }//GEN-LAST:event_createusernameFocusGained

    private void createusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createusernameFocusLost
        // TODO add your handling code here:
                if(createusername.getText().equals("Username"))
                {
                   createusername.setText("");
                }
        createusername.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_createusernameFocusLost

    private void createdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createdateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_createdateFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton backtologinform;
    private javax.swing.JPasswordField createconfirmpassword;
    private com.toedter.calendar.JDateChooser createdate;
    private javax.swing.JTextField createname;
    private javax.swing.JPasswordField createpassword;
    private javax.swing.JTextField createusername;
    private javax.swing.JTextField emailaddress;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    // End of variables declaration//GEN-END:variables
    private String prprocess(String DOB) {
        String temp = "";

        StringTokenizer tokens = new StringTokenizer(DOB);

        tokens.nextToken();

        temp += tokens.nextToken() + " ";

        temp += tokens.nextToken() + " ";

        tokens.nextToken();

        tokens.nextToken();
        temp += tokens.nextToken();

        return temp;
    }



}
