/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.project;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ubaid ur rehman
 */
public class DeleteBook extends javax.swing.JFrame {

    /**
     * Creates new form DeleteBook
     */
    public DeleteBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        Deletebookrec = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DELETE RECORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 70, 240, 120);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("BOOK NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 210, 180, 60);
        jPanel1.add(bookname);
        bookname.setBounds(330, 220, 240, 40);

        Deletebookrec.setText("DELETE");
        Deletebookrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebookrecActionPerformed(evt);
            }
        });
        jPanel1.add(Deletebookrec);
        Deletebookrec.setBounds(270, 320, 190, 30);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Icons/Mix Icon/Home.png"))); // NOI18N
        Home.setContentAreaFilled(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home);
        Home.setBounds(30, 40, 57, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Project BackGround/book Record.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -30, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeletebookrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebookrecActionPerformed
        // TODO add your handling code here:
         File oldfile=new File("Book.txt");
        File newfile=new File("temp.txt");
        FileWriter fw=null;
        FileReader fr=null;
        BufferedWriter bw=null;
        BufferedReader br=null;
        String Bname,Aname,Bedition;
        String Bnamesearch=bookname.getText()+"\n";
        try
        {
            fr=new FileReader(oldfile);
            br=new BufferedReader(fr);
            fw= new FileWriter(newfile,true);
            bw= new BufferedWriter(fw);
            
            while((Bname=br.readLine())!=null)
            {
                Bname=Bname+"\n";
                Aname=br.readLine()+"\n";
                Bedition=br.readLine()+"\n";
               
                if(!Bnamesearch.equals(Bname))
                {
                    bw.write(Bname);
                  
                    bw.write(Aname);
                 
                    bw.write(Bedition);
                 
                  
                }
            }
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.io.IOException ex) {
            Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(br!=null)
                try {
                    br.close();
            } catch (java.io.IOException ex) {
                Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(bw!=null)
                try {
                    bw.close();
            } catch (java.io.IOException ex) {
                Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(fr!=null)
                try {
                    fr.close();
            } catch (java.io.IOException ex) {
                Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(fw!=null)
                try {
                    fw.close();
            } catch (java.io.IOException ex) {
                Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
            oldfile.delete();
            File file=new File("Book.txt");
            newfile.renameTo(file);
        }
       
    }//GEN-LAST:event_DeletebookrecActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRecord().setVisible(true);
            }
        });
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebookrec;
    private javax.swing.JButton Home;
    private javax.swing.JTextField bookname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
