/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.project;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ubaid ur rehman
 */
public class SearchBookRecord extends javax.swing.JFrame {

    /**
     * Creates new form SearchBookRecord
     */
    public SearchBookRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        searchrecord = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        select1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Record");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 150, 310, 44);
        jPanel1.add(search);
        search.setBounds(500, 290, 330, 40);

        searchrecord.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        searchrecord.setText("Search");
        searchrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchrecordActionPerformed(evt);
            }
        });
        jPanel1.add(searchrecord);
        searchrecord.setBounds(600, 360, 120, 40);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Icons/Mix Icon/Home.png"))); // NOI18N
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home);
        Home.setBounds(30, 30, 57, 33);

        select1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        select1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Name", "Author" }));
        select1.setToolTipText("");
        jPanel1.add(select1);
        select1.setBounds(600, 230, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Project BackGround/book Record.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchrecordActionPerformed
        String slt=search.getText();
        FileReader fr=null;
        BufferedReader br=null;
        boolean flag=false;
        String bname,bauthor,bedition;
        if( select1.getSelectedItem() == "-Select-")
          {
           JOptionPane.showMessageDialog(this, "Select ID or Name from drop down");
          }
         else if(select1.getSelectedItem() == "Name")
           {
            try
            {
                fr=new FileReader("Book.txt");
                br=new BufferedReader(fr);
                while((bname=br.readLine())!=null)
                {
                    bname=bname+"\n";
                    bauthor=br.readLine()+"\n";
                    bedition=br.readLine()+"\n";
                    if(bname.equals(search.getText()+"\n"))
                    {
                        flag=true;
                        Book b=new Book(bname,bauthor,bedition);
                        JOptionPane.showMessageDialog(this,b.toString());
                        break;
                    }
                }
                if(flag==false)
                {
                    JOptionPane.showMessageDialog(this,"Not! Found");
                }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SearchBookRecord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SearchBookRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(br!=null)
                try {
                    br.close();
            } catch (IOException ex) {
                Logger.getLogger(SearchBookRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(fr!=null)
                try {
                    fr.close();
            } catch (IOException ex) {
                Logger.getLogger(SearchBookRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       }
         else if(select1.getSelectedItem()=="Author")
         {
            try
            {
                fr=new FileReader("Book.txt");
                br=new BufferedReader(fr);
                while((bname=br.readLine())!=null)
                {
                    bname=bname+"\n";
                    bauthor=br.readLine()+"\n";
                    bedition=br.readLine()+"\n";
                    if(bauthor.equals(search.getText()+"\n"))
                    {
                        flag=true;
                        Book b1=new Book(bname,bauthor,bedition);
                        JOptionPane.showMessageDialog(this,b1.toString());
                        break;
                        
                    }
                }
                if(flag==false)
                {
                    JOptionPane.showMessageDialog(this,"Not! Found");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SearchBookRecord.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SearchBookRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchrecordActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRecord().setVisible(true);
            }
        });

        // TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBookRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBookRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBookRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBookRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBookRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchrecord;
    private javax.swing.JComboBox<String> select1;
    // End of variables declaration//GEN-END:variables
}
